{"uuid": "df5cc234-4fc7-472d-8e89-ff1b320e2447", "children": ["bb63c73f-e42c-4300-894b-fcb3378e8ade"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=75.0.3770.142)\n\n", "trace": "  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"D:\\python\\pageAutoTest\\Testcase\\conftest.py\", line 23, in login\n    driver = webdriver.Chrome(executable_path=driver_path)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 81, in __init__\n    desired_capabilities=desired_capabilities)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1596606640985, "stop": 1596606650572}], "start": 1596606640985, "stop": 1596606650672}